CREATE OR REPLACE TABLE FIXTURES_STAGING_CLEAN AS
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY GAME_UUID
               ORDER BY DATE_TIME DESC
           ) AS rn
    FROM FIXTURES_STAGING
)
WHERE rn = 1;

CREATE OR REPLACE TABLE FIXTURES_STAGING_TYPED AS
SELECT
    * EXCLUDE (DATE_TIME, HOME_SCORE, AWAY_SCORE),
    CAST(DATE_TIME AS TIMESTAMP_NTZ) AS match_datetime,
    CAST(HOME_SCORE AS NUMBER) AS home_score,
    CAST(AWAY_SCORE AS NUMBER) AS away_score
FROM FIXTURES_STAGING_CLEAN;
